### ISSUE TITLE
Menu: Plug "Add to agenda"

### ISSUE THREAD

**Issue by AmarOk1412** [AmarOk1412/PlanEat#13]
![iPhone 13   14 - 16](https://github.com/user-attachments/assets/a6bfb32e-8bdc-484b-a7d6-d69ec261ce69)

Todo after clicking on "add to agenda"

**Comment by AmarOk1412** [comment]
# TODO

+ [x] In agenda, remove/unplanify
+ [x] In agenda => Plug delete

+ [x] In agenda, plug edit
