### ISSUE TITLE
Syncronize recipes with someone else

### ISSUE THREAD

**Issue by AmarOk1412** [AmarOk1412/PlanEat#89]
# TODO

+ [x] Document server
+ [x] Refresh page on agenda changed
+ [x] Poll every 10 min
+ [x] Crash cf below

**Comment by AmarOk1412** [comment]
Exception java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:947)
Caused by java.lang.reflect.InvocationTargetException:
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:592)
Caused by java.security.InvalidAlgorithmParameterException: java.lang.IllegalArgumentException: Unknown purpose: 64
  at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.initialize (AndroidKeyStoreKeyPairGeneratorSpi.java:347)
  at java.security.KeyPairGenerator$Delegate.initialize (KeyPairGenerator.java:697)
  at java.security.KeyPairGenerator.initialize (KeyPairGenerator.java:438)
  at com.planeat.planeat.data.Account.generateECCKeyPair (Account.java:459)
  at com.planeat.planeat.data.Account.generateAccount (Account.java:459)
  at com.planeat.planeat.data.Account.loadAccount (Account.java:459)
  at com.planeat.planeat.ui.AppModel.<init> (PlanEatApp.kt:459)
  at com.planeat.planeat.ui.PlanEatAppKt.PlanEatApp (PlanEatApp.kt:63)
  at com.planeat.planeat.ui.MainActivity$onCreate$1$1.invoke (MainActivity.kt:487)
  at com.planeat.planeat.ui.MainActivity$onCreate$1$1.invoke (MainActivity.kt:487)
  at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt:52)
  at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt:52)
  at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:233)
  at androidx.compose.material3.TextKt.ProvideTextStyle (Text.kt:77)
  at androidx.compose.material3.MaterialThemeKt$MaterialTheme$1.invoke (MaterialTheme.kt:565)
  at androidx.compose.material3.MaterialThemeKt$MaterialTheme$1.invoke (MaterialTheme.kt:565)
  at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt:52)
  at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt:52)
  at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:150)
  at androidx.compose.material3.MaterialThemeKt.MaterialTheme (MaterialTheme.kt:225)
  at com.example.compose.ThemeKt.AppTheme (Theme.kt:115)
  at com.planeat.planeat.ui.MainActivity$onCreate$1.invoke (MainActivity.java:56)
  at com.planeat.planeat.ui.MainActivity$onCreate$1.invoke (MainActivity.java:56)
  at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt:52)
  at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt:52)
  at androidx.compose.ui.platform.ComposeView.a (ComposeView.android.kt:55)
  at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke (AbstractComposeView.java:1009)
  at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke (AbstractComposeView.java:1009)
  at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt:52)
  at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt:52)
  at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:150)
  at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals (CompositionLocals.kt:309)
  at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke (AndroidCompositionLocals_android.kt:644)
  at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke (AndroidCompositionLocals_android.kt:644)
  at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt:52)
  at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt:52)
  at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:150)
  at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals (AndroidCompositionLocals.android.kt:586)
  at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke (Wrapper.android.kt:242)
  at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke (Wrapper.android.kt:242)
  at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt:52)
  at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt:52)
  at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:233)
  at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke (WrappedComposition.java:213)
  at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke (WrappedComposition.java:213)
  at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt:52)
  at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt:52)
  at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable (ActualJvm_jvm.kt:15)
  at androidx.compose.runtime.ComposerImpl.doCompose (Composer.kt:203)
  at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release (ComposerImpl.java:33)
  at androidx.compose.runtime.CompositionImpl.composeContent (Composition.kt:33)
  at androidx.compose.runtime.Recomposer.composeInitial$runtime_release (Recomposer.kt:45)
  at androidx.compose.runtime.CompositionImpl.composeInitial (Composition.kt:9)
  at androidx.compose.runtime.CompositionImpl.setContent (Composition.kt:3)
  at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke (WrappedComposition.java:74)
  at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke (WrappedComposition.java:74)
  at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable (AndroidComposeView.android.kt:7)
  at androidx.compose.ui.platform.WrappedComposition.setContent (Wrapper.android.kt:10)
  at androidx.compose.ui.platform.WrappedComposition.onStateChanged (Wrapper.android.kt:19)
  at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent (LifecycleRegistry.jvm.kt:23)
  at androidx.lifecycle.LifecycleRegistry.addObserver (LifecycleRegistry.jvm.kt:216)
  at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke (WrappedComposition.java:43)
  at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke (WrappedComposition.java:43)
  at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow (AndroidComposeView.android.kt:120)
  at android.view.View.dispatchAttachedToWindow (View.java:20479)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3489)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3496)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3496)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3496)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3496)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2435)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1948)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:8177)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:972)
  at android.view.Choreographer.doCallbacks (Choreographer.java:796)
  at android.view.Choreographer.doFrame (Choreographer.java:731)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:957)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:223)
  at android.app.ActivityThread.main (ActivityThread.java:7664)
Caused by java.lang.IllegalArgumentException: Unknown purpose: 64
  at android.security.keystore.KeyProperties$Purpose.toKeymaster (KeyProperties.java:116)
  at android.security.keystore.KeyProperties$Purpose.allToKeymaster (KeyProperties.java:141)
  at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.initialize (AndroidKeyStoreKeyPairGeneratorSpi.java:314)
